grafana:
  container_name: $GRAFANA_CONTAINER_NAME
  image: $GRAFANA_IMAGE_NAME:$GRAFANA_IMAGE_TAG
  ports:
    - "$GRAFANA_EXPOSE_HTTP:3000"
  tty: true
  volumes:
    - ./config/datasources/:/etc/grafana/provisioning/datasources/
    - ./config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    - ./config/dashboards/:/var/tmp/dashboards/
    - ./data/:/var/lib/grafana
